"""Add category and update priority

Revision ID: 31a3e2c89ac3
Revises: 351ec0c3126f
Create Date: 2026-07-16 16:41:57.702637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a3e2c89ac3'
down_revision: Union[str, Sequence[str], None] = '351ec0c3126f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
