"""Add TaskStatus Enum

Revision ID: dbf9837e6bbc
Revises: 2d33775096ce
Create Date: 2026-07-15 22:11:21.718914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf9837e6bbc'
down_revision: Union[str, Sequence[str], None] = '2d33775096ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Explicitly create ENUM type for PostgreSQL
    taskstatus_enum = sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus')
    taskstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', taskstatus_enum, nullable=False, server_default='PENDING'))
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), nullable=False, server_default='0'))
    op.drop_column('tasks', 'status')
    
    # Explicitly drop ENUM type for PostgreSQL
    taskstatus_enum = sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus')
    taskstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
