"""Add TaskStatus Enum

Revision ID: dbf9837e6bbc
Revises: 2d33775096ce
Create Date: 2026-07-15 22:11:21.718914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf9837e6bbc'
down_revision: Union[str, Sequence[str], None] = '2d33775096ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False))
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), nullable=False))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
